spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/anderson/Desktop/UnB/SI/TA1/trabalho/db;IGNORECASE=TRUE
    